# CLASSIFICATION OF IRIS FLOWER USING ITS FEATURES

## SVM - SUPPORT VECTOR MACHINES

In [29]:
from sklearn import svm
from sklearn import datasets

iris = datasets.load_iris()

iris.data

print(iris)

#type(iris)



{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [26]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
iris.target_names


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
#STORING THE INDEPENDENT VARIABLE, TWO FEATURES OF THE ARRAY

x = iris.data[:,2]

In [34]:
#THE DEPENDENT VAIABLE, The array to predict,(which SPECIFIES the species the flower belongs to), [ 0, 1 OR 2  ]

y = iris.target

In [35]:
#USING TEST SPLIT TEST

from sklearn.cross_validation import train_test_split

#TRAIN = 80%, TEST = 20%

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state= 4)


# SPECIFY A CLASSIFIER.
## THE CLASSIFIER WHICH THE FLOWER BELONGS TO.

In [70]:
#CREATING A MODEL


#CONVERTING THE ARRAYS INTO ONE-DIMENSION

x_train_mod = x_train.reshape(-1,1)
x_test_mod = x_test.reshape(-1,1)
y_train_mod = y_train.reshape(-1,1)
y_test_mod = y_test.reshape(-1,1)


#support vector machines --- model
model = svm.SVC(kernel= 'linear')

model.fit(x_train_mod, y_train_mod)

/home/bright/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [51]:
#predicting test data

y_pred_mod = model.predict(x_test_mod)

In [61]:
#TESTING THE ACCURACY SCORE

from sklearn.metrics import accuracy_score

Result = accuracy_score(y_test_mod, y_pred_mod)

print (Result)



0.9666666666666667


In [65]:
y_pred_mod

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2])

In [66]:
y_test_mod


array([[2],
       [0],
       [2],
       [2],
       [2],
       [1],
       [1],
       [0],
       [0],
       [2],
       [0],
       [0],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2]])

In [67]:
x_test_mod

array([[5.6],
       [1.7],
       [6.1],
       [6.6],
       [6.3],
       [4.5],
       [5.1],
       [1.2],
       [1.7],
       [5.1],
       [1.6],
       [1.6],
       [1.4],
       [4.7],
       [5. ],
       [1.5],
       [3.5],
       [1.3],
       [1.9],
       [4.9],
       [1.2],
       [5.7],
       [4.5],
       [1.6],
       [1.6],
       [1.5],
       [1.3],
       [1.3],
       [1.7],
       [5.1]])

In [68]:
x_train_mod

array([[4.5],
       [1.4],
       [5.8],
       [1.4],
       [3.3],
       [5.7],
       [6. ],
       [4. ],
       [4.7],
       [1.6],
       [6.1],
       [1.5],
       [4.4],
       [1.5],
       [5.6],
       [1.1],
       [1.5],
       [4.2],
       [4.6],
       [5.5],
       [1.5],
       [3.9],
       [6.9],
       [5.6],
       [4.3],
       [4.2],
       [1.6],
       [3.6],
       [5. ],
       [4.4],
       [1.4],
       [4.1],
       [1.5],
       [4.3],
       [5.5],
       [5. ],
       [5.1],
       [4.5],
       [1.5],
       [4.5],
       [5.7],
       [1.5],
       [3.8],
       [6. ],
       [1.4],
       [4.9],
       [4.6],
       [5.1],
       [4.9],
       [1.5],
       [5.6],
       [4.5],
       [5.9],
       [1.3],
       [5.3],
       [4. ],
       [5.4],
       [3.9],
       [5.1],
       [4. ],
       [4.8],
       [5.4],
       [4.1],
       [4.4],
       [5.1],
       [4. ],
       [4.1],
       [1. ],
       [5.6],
       [1.7],
       [4.8],
      

In [69]:
y_train_mod

array([[1],
       [0],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [2],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [1],
       [1],
       [0],
    

In [72]:
y_test

array([2, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2])